<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Modules.Parcels</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules.Parcels.Domain\Modules.Parcels.Domain.csproj" />
    <ProjectReference Include="..\Modules.Parcels.TestBase\Modules.Parcels.TestBase.csproj" />
  </ItemGroup>


</Project>
